services:
  hidden-queen:
    image: hidden-queen
    container_name: hidden-queen
    build: .
    ports:
      - "7070:3000" 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    environment:
      NODE_ENV: production 
    restart: unless-stopped

